name: apps/hyparquet-demo
on:
  push:
    paths:
      - 'apps/hyparquet-demo/**'
      - '.github/workflows/ci_apps_hyparquet_demo.yml'

defaults:
  run:
    working-directory: ./apps/hyparquet-demo

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm i
      - run: npm run build
        working-directory: ./packages/utils
      - run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm i
      - run: npm run build
        working-directory: ./packages/utils
      - run: tsc

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm i
      - run: npm run build
        working-directory: ./packages/utils
      - run: npm run coverage

  buildcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm i
      - run: npm run build
        working-directory: ./packages/utils
      - run: npm run build