name: apps/hyparquet-demo
on:
  push:
    paths:
      - 'apps/hyparquet-demo/**'
      - '.github/workflows/_common_jobs.yml'
      - '.github/workflows/ci_apps_hyparquet_demo.yml'
      - 'shared.eslint.config.js'
jobs:
  ci:
    uses: ./.github/workflows/_common_jobs.yml
    with:
      working-directory: apps/hyparquet-demo
