name: apps/hightable-demo
on:
  push:
    paths:
      - 'apps/hightable-demo/**'
      - '.github/workflows/_common_jobs.yml'
      - '.github/workflows/ci_apps_hightable_demo.yml'
      - 'eslint.config.js'
      - 'package.json'
jobs:
  ci:
    uses: ./.github/workflows/_common_jobs.yml
    with:
      workspace: hightable-demo
