name: apps/cli
on:
  push:
    paths:
      - 'packages/components/**'
      - 'apps/cli/**'
      - '.github/workflows/ci_apps_cli.yml'
      - 'shared.eslint.config.js'

defaults:
  run:
    working-directory: ./apps/cli

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i
      - run: |
          npm i
          npm run build
        working-directory: ./packages/components
      - run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i
      - run: |
          npm i
          npm run build
        working-directory: ./packages/components
      - run: tsc

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i
      - run: |
          npm i
          npm run build
        working-directory: ./packages/components
      - run: npm run coverage

  buildcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i
      - run: |
          npm i
          npm run build
        working-directory: ./packages/components
      - run: npm run build
