name: CI in the components package
on:
  pull_request:
    paths:
      - 'packages/components/**'
      - '.github/workflows/ci_components.yml'
  push:
    paths:
      - 'packages/components/**'
      - '.github/workflows/ci_components.yml'

defaults:
  run:
    working-directory: ./packages/components

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i
      - run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i
      - run: tsc

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i
      - run: npm run coverage
