name: packages/components
on:
  push:
    paths:
      - 'packages/components/**'
      - 'packages/utils/**'
      - '.github/workflows/ci_packages_components.yml'

defaults:
  run:
    working-directory: ./packages/components

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i
      - run: npm run build
        working-directory: ./packages/utils
      - run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i
      - run: npm run build
        working-directory: ./packages/utils
      - run: tsc

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i
      - run: npm run build
        working-directory: ./packages/utils
      - run: npm run coverage

  buildcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i
      - run: npm run build
        working-directory: ./packages/utils
      - run: npm run build
