name: packages/utils
on:
  push:
    paths:
      - 'packages/utils/**'
      - '.github/workflows/ci_packages_utils.yml'
      - 'shared.eslint.config.js'
jobs:
  ci:
    uses: ./.github/workflows/_common_jobs.yml
    with:
      working-directory: packages/utils
