name: packages/components
on:
  pull_request:
    paths:
      - 'packages/components/**'
      - '.github/workflows/_common_jobs.yml'
      - '.github/workflows/ci_packages_components.yml'
      - 'eslint.config.js'
      - 'package.json'
jobs:
  ci:
    uses: ./.github/workflows/_common_jobs.yml
    with:
      workspace: '@hyparam/components'
